[project]
name = "breast-cancer-detection-flax-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "google-cloud-pipeline-components>=2.17.0",
    "kfp>=2.7.0",
]
